//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingRover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RatingRover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;movielist&gt;
        ///&lt;movie&gt;
        ///	&lt;title&gt;Adventures of Casanova &lt;/title&gt;
        ///	&lt;year&gt;1948&lt;/year&gt;
        ///	&lt;length&gt;83 min&lt;/length&gt;
        ///	&lt;certification&gt;Approved&lt;/certification&gt;
        ///	&lt;director&gt;Roberto Gavaldn&lt;/director&gt;
        ///	&lt;rating&gt;1&lt;/rating&gt;
        ///	&lt;genre&gt;Action&lt;/genre&gt;
        ///	&lt;genre&gt;Adventure&lt;/genre&gt;
        ///	&lt;genre&gt;History&lt;/genre&gt;
        ///	&lt;genre&gt;Romance&lt;/genre&gt;
        ///	&lt;genre&gt;War&lt;/genre&gt;
        ///	&lt;actor&gt;Arturo de C  rdova&lt;/actor&gt;
        ///	&lt;actor&gt;Lucille Bremer&lt;/actor&gt;
        ///	&lt;actor&gt;Turhan Bey&lt;/actor&gt;
        ///	&lt;actor&gt;John Sutton&lt;/actor&gt;
        ///	&lt;actor&gt;George Tobias&lt;/actor&gt;
        ///&lt;/movie&gt;
        ///&lt;movie&gt;
        ///	&lt;ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string movies {
            get {
                return ResourceManager.GetString("movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;users&gt;
        ///&lt;/users&gt;
        ///.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
